# Generated by Django 3.2.4 on 2021-06-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
